export const TUNTAS_SET_USER = 'TUNTAS_SET_USER';
export const TUNTAS_RESET = 'TUNTAS_RESET';

export const ANALYTICS_IDENTITY = 'ANALYTICS_IDENTITY';
export const ANALYTICS_RESET = 'ANALYTICS_RESET';
